name: Deploy App

on:
  push:
    branches:
      - main
  
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Install Deps
        run: npm ci
      - name: Run Tests for Deploy
        run: npm run test
